FROM oryd/hydra:v2.0.3
LABEL description="hydra server"
EXPOSE 4444 4445
ADD [ "./hydra", "/etc/config/hydra" ]
ENV URLS_LOGIN=http://172.17.14.24:8080/login
ENV URLS_CONSENT=http://172.17.14.24:8080/consent
ENV URLS_LOGOUT=http://172.17.14.24:8080/logout
ENTRYPOINT [ "hydra" ]
CMD [ "serve","-c","/etc/config/hydra/hydra.yml","all","--dev" ]